config/routes.rb
Ideashouter::Application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :shouts
  end

  root :to => "shouts#index"

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                   :integer         not null, primary key
#  email                :string(255)     default(""), not null, indexed
#  encrypted_password   :string(128)     default(""), not null
#  password_salt        :string(255)     default(""), not null
#  reset_password_token :string(255)     indexed
#  remember_token       :string(255)
#  remember_created_at  :datetime
#  sign_in_count        :integer         default(0)
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  current_sign_in_ip   :string(255)
#  last_sign_in_ip      :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/shout.rb
# == Schema Information
#
# Table name: shouts
#
#  id         :integer         not null, primary key
#  message    :string(255)
#  upvotes    :integer
#  downvotes  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Shout < ActiveRecord::Base
  validates :message, :presence => true
  
  def to_s
    message
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_admin!
  
end

app/controllers/admin/shouts_controller.rb
class Admin::ShoutsController < Admin::BaseController
  # GET /admin/shouts
  def index
    @shouts = Shout.all
  end
  
  # GET /admin/shouts/new
  def new
    @shout = Shout.new
  end
  
  # GET /admin/shouts/:id/edit
  def edit
    
  end
  
  # POST /admin/shouts
  def create
    @shout = Shout.create! params[:shout]
    redirect_to admin_shouts_path
  end
  
  # PUT /admin/shouts/:id
  def update
    
  end
  
  # DELETE /admin/shouts/:id
  def destroy
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  # GET /shouts
  # GET /
  def index
    @shout = Shout.order('RANDOM()').first
    @shout = "No shouts! :(" if @shout.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/admin/shouts/index.html.haml
=link_to "ADD SHOUT!", new_admin_shout_path
%table
  -@shouts.each do |shout|
    %tr
      %td=shout
      %td
        %ul
          %li=link_to 'edit', edit_admin_shout_path(shout)
          %li=link_to 'delete', admin_shout_path(shout), :method => :delete

app/views/admin/shouts/new.html.haml
-form_for [:admin, @shout] do |f|
  =f.text_field :message
  =f.submit 'SHOUT!'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Ideashouter
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
  %body
    #flash
      - [:notice, :alert].each do |flash|
        - output = send(flash)
        - if output.present?
          %div{:class => flash}= output
          
    %nav#admin
      -if admin_signed_in?
        = link_to "Admin", admin_shouts_path
        |
        =link_to "Signout", destroy_admin_session_path
      - else
        =link_to "Login", new_admin_session_path
        
    = yield

app/views/shouts/index.html.haml
%h1#shout=@shout